runtime: nodejs10
handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: /\1
    upload: /(.*\..+)$

  # Catch all handler to serve index.html for all other URLs
  - url: /.*
    static_files: /index.html
    upload: /index.html

